apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-api-account
  namespace: app
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: app
  name: open-api-service-reader
rules:
- apiGroups: [""]
  resources: ["services","leases", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: open-api-service-reader
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: open-api-account
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: app
roleRef:
  kind: ClusterRole
  name: open-api-service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-api-role
  namespace: app
rules:
- apiGroups: [""]
  resources: ["leases", "configmaps"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-api-rolebinding
  namespace: app
subjects:
- kind: ServiceAccount
  name: open-api-account
  namespace: app
roleRef:
  kind: Role
  name: open-api-role
  apiGroup: rbac.authorization.k8s.io
